### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by baarkerlounger** [benjamintd/benmaps.fr#86]
Running:

`yarn`
`yarn start`

and navigating to `http://localhost:5000`

Gives me: `404  The requested path could not be found`

Is there any additional setup needed to get this running?

**Comment by benjamintd** [comment]
Can you try running `yarn dev` ? Or alternatively, to build the project first:
```
yarn 
yarn build
yarn start
```

If this still does not work, perhaps are you missing a .env file with the required environment variables (see .env.sample that I just pushed to master).
